import { writeFileSync } from 'fs';
import { dedent } from 'tslint/lib/utils';

const util = require('util');
const exec = util.promisify(require('child_process').exec);

async function createVersionsFile(filename: string) {
  const tag      = (await exec('git tag -l --points-at HEAD')).stdout.toString().trim();
  const revision = (await exec('git rev-parse --short HEAD')).stdout.toString().trim();

  const content = dedent`
      // DO NOT EDIT
      // this file is generated by git.version.ts
      export const version = {
        tag: '${tag}',
        revision: '${revision}'
      };`;

  writeFileSync(filename, content, {encoding: 'utf8'});
}

createVersionsFile('src/environments/version.ts');
